name: CI
on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  docs:
    uses: BrainXio/cicd/.github/workflows/doc-quality.yml@v1
    with:
      md-paths: "."
      yaml-paths: ".github"

  starter:
    uses: BrainXio/cicd/.github/workflows/starter-checks.yml@v1
